apiVersion: apps/v1
kind: Deployment
metadata:
  name: knx-deployment
  namespace: default
  labels:
    app: knorex-assign
spec:
  replicas: 1
  selector:
    matchLabels:
      app: knorex-assign
  template:
    metadata:
      labels:
        app: knorex-assign
    spec:
      containers:
      - name: knorex-assign
        image: importhuman/kv-store
        ports:
        - containerPort: 8080
        lifecycle:
          preStop:
            exec:
              command: ["sleep", "15"]
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 2
          periodSeconds: 5
          successThreshold: 1
      terminationGracePeriodSeconds: 45

---
apiVersion: v1
kind: Service
metadata:
  name: knx-svc
spec:
  type: NodePort
  selector:
    app: knorex-assign
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31000