# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  aws-cli: circleci/aws-cli@3.1.3
  helm: circleci/helm@2.0.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
        auth:
          username: $docker_username
          password: $docker_pass
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - run: 
          name: build and push docker image
          command: |
            docker login -u $docker_username -p $docker_pass
            docker build -t lehuuan18/knorex-assign:latest .
            docker push lehuuan18/knorex-assign:latest 
  deploy:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          aws-access-key-id: aws_access_key
          aws-secret-access-key: aws_secret_key
          aws-region: aws_region_name
          profile-name: default
      - aws-cli/role-arn-setup:
          profile-name: new-profile
          role-arn: 'arn:aws:iam::102979132623:role/Admin'
          source-profile: default
      - run: 
          name: eks update config
          command: aws eks update-kubeconfig --region ap-southeast-1 --name knorex-k8s
      

workflows:
  build_and_deploy:
    jobs:
      - build
      - deploy
