apiVersion: v1
kind: Service
metadata:
  name: {{ include "knorex-assign.fullname" . }}
  labels:
    {{- include "knorex-assign.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      name: http
      targetPort: {{ .Values.service.port }}
      nodePort: {{ .Values.node.port }}
  selector:
    {{- include "knorex-assign.selectorLabels" . | nindent 4 }}
