apiVersion: v1
kind: Service
metadata:
  name: {{ include "knorex-assign.fullname" . }}
  labels:
    {{- include "knorex-assign.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodePort: {{ .Values.node.port }}
  selector:
    app: "{{ include "knorex-assign.name" . }}"
    release: {{ .Release.Name }}
